GET http://localhost:3000/articles

###

GET http://localhost:3000/articles/6493c44e049cac26d2fcadaf

###

POST http://localhost:3000/articles
Content-Type: application/json

{
	"title": "SQL For Testing Recipts",
	"content": "Here goes a long SQL script...",
	"category": "SQL",
	"isActive": true
}

###

DELETE http://localhost:3000/articles/6493c44e049cac26d2fcadaf

###

PATCH http://localhost:3000/articles/64950f511769925de340a4f3
Content-Type: application/json

{
	"title": "SQL Testing Codes"
}

